import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildStaticExport, desktopRoot, runCommand, stageExportedMainview, workspaceRoot } from './build-utils';
import type { ReleaseManifest } from './release-types';
import { inferPlatformKey, isInstallerArtifact } from './release-utils';

type DesktopPackageJson = {
  version: string;
};

const desktopPackageJsonPath = join(desktopRoot, 'package.json');
const artifactDir = join(desktopRoot, 'artifacts');
const releaseBaseUrl =
  process.env['CONIVA_RELEASE_BASE_URL'] ?? 'https://updates.coniva.app/releases';

const requestedVersion = readArgValue('--version');
const releaseNotes =
  readArgValue('--notes') ??
  process.env['RELEASE_NOTES'] ??
  'Desktop release build generated by the Coniva release pipeline.';

const currentPackageJson = readDesktopPackageJson();
const nextVersion = requestedVersion ?? incrementPatch(currentPackageJson.version);

writeDesktopPackageJson({
  ...currentPackageJson,
  version: nextVersion,
});

await buildStaticExport();
stageExportedMainview();
await runCommand(['corepack', 'pnpm', '--dir', 'desktop', 'dist'], workspaceRoot);

const summaryManifest = createSummaryManifest(nextVersion, releaseNotes);
writeFileSync(join(artifactDir, 'latest.json'), JSON.stringify(summaryManifest, null, 2));

console.log(`Release ${nextVersion} prepared.`);
console.log(`Summary manifest: ${join(artifactDir, 'latest.json')}`);

function readDesktopPackageJson(): DesktopPackageJson {
  return JSON.parse(readFileSync(desktopPackageJsonPath, 'utf8')) as DesktopPackageJson;
}

function writeDesktopPackageJson(pkg: DesktopPackageJson) {
  writeFileSync(desktopPackageJsonPath, JSON.stringify(pkg, null, 2) + '\n');
}

function incrementPatch(version: string) {
  const match = version.match(/^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/);
  if (!match) {
    throw new Error(`Unsupported desktop version format: ${version}`);
  }

  const major = Number.parseInt(match[1]!, 10);
  const minor = Number.parseInt(match[2]!, 10);
  const patch = Number.parseInt(match[3]!, 10) + 1;
  return `${major}.${minor}.${patch}`;
}

function createSummaryManifest(version: string, releaseNotesText: string): ReleaseManifest {
  const files = readdirSync(artifactDir).filter((file) => file !== 'latest.json');
  const platforms: ReleaseManifest['platforms'] = {};

  for (const file of files) {
    const platformKey = inferPlatformKey(file);
    if (!platformKey) continue;

    const entry = (platforms[platformKey] ??= {
      downloadUrl: null,
      files: [],
    });

    entry.files.push(file);
    if (!entry.downloadUrl && isInstallerArtifact(file)) {
      entry.downloadUrl = `${releaseBaseUrl.replace(/\/+$/, '')}/${file}`;
    }
  }

  return {
    version,
    releaseDate: new Date().toISOString(),
    releaseNotes: releaseNotesText,
    platforms,
  };
}

function readArgValue(flag: string) {
  const exactArg = Bun.argv.find((arg) => arg.startsWith(`${flag}=`));
  if (exactArg) {
    return exactArg.slice(flag.length + 1).trim() || undefined;
  }

  const index = Bun.argv.findIndex((arg) => arg === flag);
  if (index === -1) return undefined;
  const nextValue = Bun.argv[index + 1];
  return nextValue?.trim() || undefined;
}
