/**
 * Style Dictionary v4 build for Hiero component tokens.
 *
 * Source of truth: tokens/component.tokens.json (DTCG W3C format).
 * Theme overrides: tokens/themes/<id>.tokens.json.
 *
 * Outputs:
 *   app/_generated/component-tokens.css   — :root + [data-theme] blocks
 *   lib/_generated/component-tokens.ts    — TS const map of token paths
 *
 * Run: pnpm tokens:build
 *
 * The output `:root` block here REPLACES the inline component-token
 * block in app/globals.css. globals.css imports the generated file
 * after the semantic-token blocks. To add a theme, drop a JSON file in
 * tokens/themes/ and add it to THEMES below.
 */

import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import StyleDictionary from 'style-dictionary';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const THEMES = ['minimal', 'brutalist'];

/* ── Custom format: theme-aware CSS variables ───────────────────────── */

StyleDictionary.registerFormat({
  name: 'css/hiero-component-tokens',
  format: ({ dictionary, options }) => {
    const selector = options.selector ?? ':root';
    const banner =
      '/* Generated by tokens/style-dictionary.config.mjs — do not edit by hand. */\n';
    const lines = dictionary.allTokens
      .filter((token) => !token.path[0]?.startsWith('semantic')) // semantic entries are pointers only
      .map((token) => {
        const name = `--${token.path.join('-')}`;
        const value = token.$value ?? token.value;
        return `  ${name}: ${value};`;
      });
    return `${banner}${selector} {\n${lines.join('\n')}\n}\n`;
  },
});

/* ── Custom format: TS const map for IDE autocomplete ───────────────── */

StyleDictionary.registerFormat({
  name: 'ts/hiero-token-names',
  format: ({ dictionary }) => {
    const banner =
      '// Generated by tokens/style-dictionary.config.mjs — do not edit by hand.\n';
    const entries = dictionary.allTokens
      .filter((token) => !token.path[0]?.startsWith('semantic'))
      .map((token) => {
        const key = token.path.join('-');
        return `  '${key}': '--${key}',`;
      });
    return (
      banner +
      '\n/**\n * Map of component-token logical names to their CSS variable names.\n * Use for IDE autocomplete and refactor-safe references in code.\n */\nexport const tokens = {\n' +
      entries.join('\n') +
      '\n} as const;\n\nexport type TokenName = keyof typeof tokens;\n'
    );
  },
});

/* ── Build the default (classic) theme ──────────────────────────────── */

const baseConfig = {
  source: [
    resolve(ROOT, 'tokens/semantic.tokens.json'),
    resolve(ROOT, 'tokens/component.tokens.json'),
  ],
  log: { warnings: 'disabled', verbosity: 'silent' },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: resolve(ROOT, 'app/_generated') + '/',
      files: [
        {
          destination: 'component-tokens.css',
          format: 'css/hiero-component-tokens',
          options: { selector: ':root' },
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath: resolve(ROOT, 'lib/_generated') + '/',
      files: [
        {
          destination: 'component-tokens.ts',
          format: 'ts/hiero-token-names',
        },
      ],
    },
  },
};

const baseSd = new StyleDictionary(baseConfig);
await baseSd.buildAllPlatforms();

/* ── Append each theme block to component-tokens.css ─────────────────── */

const fs = await import('node:fs/promises');
const cssPath = resolve(ROOT, 'app/_generated/component-tokens.css');
let combined = await fs.readFile(cssPath, 'utf-8');

for (const theme of THEMES) {
  const themeSd = new StyleDictionary({
    source: [
      resolve(ROOT, 'tokens/semantic.tokens.json'),
      resolve(ROOT, 'tokens/component.tokens.json'),
      resolve(ROOT, `tokens/themes/${theme}.tokens.json`),
    ],
    log: { warnings: 'disabled', verbosity: 'silent' },
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: resolve(ROOT, 'app/_generated') + '/',
        files: [
          {
            destination: `component-tokens.${theme}.css`,
            format: 'css/hiero-component-tokens',
            options: { selector: `[data-theme='${theme}']` },
          },
        ],
      },
    },
  });
  await themeSd.buildAllPlatforms();
  const themeCss = await fs.readFile(
    resolve(ROOT, `app/_generated/component-tokens.${theme}.css`),
    'utf-8',
  );
  combined +=
    '\n' +
    themeCss
      .split('\n')
      .filter((line) => !line.startsWith('/* Generated'))
      .join('\n');
  await fs.unlink(resolve(ROOT, `app/_generated/component-tokens.${theme}.css`));
}

await fs.writeFile(cssPath, combined, 'utf-8');
console.log('✓ component-tokens.css regenerated (classic + ' + THEMES.join(', ') + ').');
