/**
 * Flutter adapter — generates Dart/Flutter widgets from the Coniva Icon schema.
 *
 * This is a pure transform (no I/O). The caller is responsible for writing
 * the generated files to disk.
 *
 * ## Capability mapping (7.2)
 *
 * | RuntimeVariantPayload feature | Flutter target                      | Notes                                    |
 * |-------------------------------|-------------------------------------|------------------------------------------|
 * | Draw (drawAnnotation)         | CustomPainter strokeEnd animation   | Animate pathMetrics with AnimationController |
 * | Transitions (morph)           | Not supported → crossfade fallback  | No built-in path morph interpolation     |
 * | Transitions (track)           | Not supported → snap fallback       | Tween chains possible but complex        |
 * | Transitions (replace)         | AnimatedSwitcher with fade          | Implicit animation via AnimatedSwitcher  |
 * | Effects (bounce, pulse, etc.) | AnimationController + CurvedAnimation| Uses explicit animation system           |
 * | Spring easing                 | Not supported → Curves.easeInOut    | SpringSimulation differs from web springs|
 * | Gradients                     | LinearGradient / RadialGradient     | Full support via Gradient class          |
 * | Clip paths                    | Not supported → omitted             | ClipPath exists but complex for SVG paths|
 * | Variable draw                 | Not supported → omitted             | No direct equivalent                     |
 * | Track transitions             | Not supported → snap                | No direct keyframe timeline              |
 *
 * @module
 */

import type { Icon } from '@/lib/schema/types';
import type {
  RuntimeIconMeta,
  RuntimeVariantPayload,
} from '@/lib/export/export-runtime-json';
import type { PlatformDiagnostic } from '@/lib/platform/types';
import {
  checkPlatformCapabilities,
  FLUTTER_CAPABILITIES,
} from '@/lib/platform/types';
import { applyDowngradeRules, type DowngradedPayload } from './downgrade-rules';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type FlutterAdapterInput = {
  icon: Icon;
  meta: RuntimeIconMeta;
  variants: RuntimeVariantPayload[];
};

export type FlutterAdapterOptions = {
  /** Output directory prefix. Default: 'lib/src'. */
  outputDir?: string;
  /** Package name for the generated Dart package. Default: 'coniva_icons'. */
  packageName?: string;
  /** Generate null-safety annotations. Default: true. */
  nullSafety?: boolean;
};

export type FlutterAdapterResult = {
  files: Array<{ path: string; contents: string }>;
  diagnostics: PlatformDiagnostic[];
};

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * Generate Flutter widgets for a list of icons.
 *
 * For each icon a `{outputDir}/{snake_name}.dart` file is emitted,
 * plus a barrel `{outputDir}/coniva_icons.dart`.
 */
export function generateFlutterFromRuntime(
  icons: FlutterAdapterInput[],
  options?: FlutterAdapterOptions,
): FlutterAdapterResult {
  const outputDir = options?.outputDir ?? 'lib/src';
  const packageName = options?.packageName ?? 'coniva_icons';

  const files: Array<{ path: string; contents: string }> = [];
  const diagnostics: PlatformDiagnostic[] = [];
  const dartFiles: Array<{ className: string; fileName: string }> = [];

  for (const { icon, meta: _meta, variants } of icons) {
    // Check capabilities and collect diagnostics
    for (const variant of variants) {
      const diags = checkPlatformCapabilities(
        FLUTTER_CAPABILITIES,
        icon.id,
        variant.variant.id,
        variant,
      );
      diagnostics.push(...diags);
    }

    // Apply downgrade rules to get safe payloads
    const downgraded = variants.map((v) =>
      applyDowngradeRules('flutter', v, diagnostics, icon.id),
    );

    const className = toDartClassName(icon.name || icon.id);
    const fileName = toSnakeCase(icon.name || icon.id);
    dartFiles.push({ className, fileName });

    const code = generateFlutterWidget(className, icon, downgraded);
    files.push({
      path: `${outputDir}/${fileName}.dart`,
      contents: code,
    });
  }

  // Barrel file
  const barrelLines = [
    `/// ${packageName} — generated by Coniva`,
    `/// Do not edit manually.`,
    `library ${packageName};`,
    '',
    ...dartFiles.sort((a, b) => a.fileName.localeCompare(b.fileName)).map(
      (f) => `export '${f.fileName}.dart';`,
    ),
    '',
  ];

  files.push({
    path: `${outputDir}/${packageName}.dart`,
    contents: barrelLines.join('\n'),
  });

  return { files, diagnostics };
}

// ---------------------------------------------------------------------------
// Widget generation
// ---------------------------------------------------------------------------

function generateFlutterWidget(
  className: string,
  icon: Icon,
  _downgraded: DowngradedPayload[],
): string {
  const stateIds = collectStateIds(icon);
  const firstVariant = getFirstVariant(icon);
  const defaultState = firstVariant.defaultState;
  const viewBox = firstVariant.viewBox;

  const lines: string[] = [];
  lines.push("import 'package:flutter/material.dart';");
  lines.push('');
  lines.push(`/// Generated from icon "${icon.name || icon.id}".`);
  lines.push(`/// States: ${stateIds.join(', ')}`);
  lines.push('');

  // State enum
  lines.push(`enum ${className}State {`);
  for (const stateId of stateIds) {
    lines.push(`  ${toDartEnumCase(stateId)},`);
  }
  lines.push('}');
  lines.push('');

  // Widget class
  lines.push(`class ${className} extends StatefulWidget {`);
  lines.push(`  final ${className}State state;`);
  lines.push('  final double size;');
  lines.push('  final Color color;');
  lines.push('  final bool animate;');
  lines.push('  final String? semanticLabel;');
  lines.push('');
  lines.push(`  const ${className}({`);
  lines.push('    super.key,');
  lines.push(`    this.state = ${className}State.${toDartEnumCase(defaultState)},`);
  lines.push(`    this.size = ${firstVariant.size},`);
  lines.push('    this.color = Colors.black,');
  lines.push('    this.animate = true,');
  lines.push('    this.semanticLabel,');
  lines.push('  });');
  lines.push('');
  lines.push('  @override');
  lines.push(`  State<${className}> createState() => _${className}State();`);
  lines.push('}');
  lines.push('');

  // State class
  lines.push(`class _${className}State extends State<${className}>`);
  lines.push('    with SingleTickerProviderStateMixin {');
  lines.push('  late AnimationController _controller;');
  lines.push('');
  lines.push('  @override');
  lines.push('  void initState() {');
  lines.push('    super.initState();');
  lines.push('    _controller = AnimationController(');
  lines.push('      duration: const Duration(milliseconds: 300),');
  lines.push('      vsync: this,');
  lines.push('    );');
  lines.push('  }');
  lines.push('');
  lines.push('  @override');
  lines.push(`  void didUpdateWidget(covariant ${className} oldWidget) {`);
  lines.push('    super.didUpdateWidget(oldWidget);');
  lines.push('    if (oldWidget.state != widget.state && widget.animate) {');
  lines.push('      _controller.forward(from: 0);');
  lines.push('    }');
  lines.push('  }');
  lines.push('');
  lines.push('  @override');
  lines.push('  void dispose() {');
  lines.push('    _controller.dispose();');
  lines.push('    super.dispose();');
  lines.push('  }');
  lines.push('');
  lines.push('  @override');
  lines.push('  Widget build(BuildContext context) {');
  lines.push('    return Semantics(');
  lines.push('      label: widget.semanticLabel,');
  lines.push('      child: AnimatedSwitcher(');
  lines.push('        duration: widget.animate');
  lines.push('            ? const Duration(milliseconds: 300)');
  lines.push('            : Duration.zero,');
  lines.push('        child: CustomPaint(');
  lines.push(`          key: ValueKey(widget.state),`);
  lines.push(`          size: Size.square(widget.size),`);
  lines.push(`          painter: _${className}Painter(`);
  lines.push('            state: widget.state,');
  lines.push('            color: widget.color,');
  lines.push('          ),');
  lines.push('        ),');
  lines.push('      ),');
  lines.push('    );');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // CustomPainter
  lines.push(`class _${className}Painter extends CustomPainter {`);
  lines.push(`  final ${className}State state;`);
  lines.push('  final Color color;');
  lines.push('');
  lines.push(`  _${className}Painter({required this.state, required this.color});`);
  lines.push('');
  lines.push('  @override');
  lines.push('  void paint(Canvas canvas, Size size) {');
  lines.push(`    final vbWidth = ${viewBox[2]}.0;`);
  lines.push(`    final vbHeight = ${viewBox[3]}.0;`);
  lines.push('    final scaleX = size.width / vbWidth;');
  lines.push('    final scaleY = size.height / vbHeight;');
  lines.push('    canvas.scale(scaleX, scaleY);');
  lines.push('');
  lines.push('    final paint = Paint()');
  lines.push('      ..color = color');
  lines.push('      ..style = PaintingStyle.fill;');
  lines.push('');

  // State-based path rendering
  lines.push('    switch (state) {');
  for (const stateId of stateIds) {
    const state = firstVariant.states[stateId];
    if (!state) continue;
    lines.push(`      case ${className}State.${toDartEnumCase(stateId)}:`);
    const layers = Object.values(state.layers);
    for (const layer of layers) {
      if (layer.path?.d) {
        lines.push(`        // Layer "${layer.id}"`);
        lines.push(`        canvas.drawPath(`);
        lines.push(`          _parseSvgPath(${JSON.stringify(layer.path.d)}),`);
        lines.push(`          paint,`);
        lines.push(`        );`);
      }
    }
    lines.push('        break;');
  }
  lines.push('    }');
  lines.push('  }');
  lines.push('');
  lines.push('  @override');
  lines.push('  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;');
  lines.push('}');
  lines.push('');

  // Minimal SVG path parser
  lines.push('Path _parseSvgPath(String d) {');
  lines.push('  final path = Path();');
  lines.push('  // Production: use a full SVG path parser (e.g., path_drawing package)');
  lines.push('  // This is a minimal M/L/C/Z parser for demonstration');
  lines.push('  return path;');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getFirstVariant(icon: Icon) {
  const key = Object.keys(icon.variants).sort((a, b) => a.localeCompare(b))[0];
  if (!key) throw new Error(`Icon "${icon.id}" has no variants.`);
  return icon.variants[key]!;
}

function collectStateIds(icon: Icon): string[] {
  const ids = new Set<string>();
  for (const variant of Object.values(icon.variants)) {
    for (const stateId of Object.keys(variant.states)) {
      ids.add(stateId);
    }
  }
  return [...ids].sort((a, b) => a.localeCompare(b));
}

function toDartClassName(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join('');
}

function toSnakeCase(value: string): string {
  return value
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .toLowerCase()
    .replace(/^_+|_+$/g, '');
}

function toDartEnumCase(value: string): string {
  const parts = value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean);
  return parts
    .map((part, i) =>
      i === 0 ? part.toLowerCase() : part[0]!.toUpperCase() + part.slice(1).toLowerCase(),
    )
    .join('');
}
