/**
 * Swift adapter — generates SwiftUI components from the Coniva Icon schema.
 *
 * This is a pure transform (no I/O). The caller is responsible for writing
 * the generated files to disk.
 *
 * ## Capability mapping (7.1)
 *
 * | RuntimeVariantPayload feature | SwiftUI/UIKit target               | Notes                                    |
 * |-------------------------------|-------------------------------------|------------------------------------------|
 * | Draw (drawAnnotation)         | CAShapeLayer strokeEnd animation    | Animates strokeEnd from 0→1              |
 * | Transitions (morph)           | Not supported → crossfade fallback  | SwiftUI lacks path morph interpolation   |
 * | Transitions (track)           | Not supported → snap fallback       | No direct keyframe timeline equivalent   |
 * | Transitions (replace)         | withAnimation { state = newState }  | Implicit animation via SwiftUI           |
 * | Effects (bounce, pulse, etc.) | withAnimation(.spring) + modifiers  | Uses implicit animation system           |
 * | Spring easing                 | Not supported → ease-in-out fallback| SwiftUI springs differ in parameterization|
 * | Gradients                     | LinearGradient / RadialGradient     | Full support                             |
 * | Clip paths                    | .clipShape() modifier               | Full support                             |
 * | Variable draw                 | Not supported → omitted             | No direct equivalent                     |
 * | Track transitions             | Not supported → snap                | No direct keyframe timeline              |
 *
 * @module
 */

import type { Icon } from '@/lib/schema/types';
import type {
  RuntimeIconMeta,
  RuntimeVariantPayload,
} from '@/lib/export/export-runtime-json';
import type { PlatformDiagnostic } from '@/lib/platform/types';
import {
  checkPlatformCapabilities,
  SWIFT_CAPABILITIES,
} from '@/lib/platform/types';
import { applyDowngradeRules, type DowngradedPayload } from './downgrade-rules';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type SwiftAdapterInput = {
  icon: Icon;
  meta: RuntimeIconMeta;
  variants: RuntimeVariantPayload[];
};

export type SwiftAdapterOptions = {
  /** Target framework: 'swiftui' (default) or 'uikit'. */
  framework?: 'swiftui' | 'uikit';
  /** Minimum iOS deployment target. Default: '16.0'. */
  minimumDeploymentTarget?: string;
  /** Output directory prefix. Default: 'Sources'. */
  outputDir?: string;
  /** Package name for the generated Swift package. Default: 'ConivaIcons'. */
  packageName?: string;
};

export type SwiftAdapterResult = {
  files: Array<{ path: string; contents: string }>;
  diagnostics: PlatformDiagnostic[];
};

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * Generate Swift components for a list of icons.
 *
 * For each icon a `{outputDir}/{ComponentName}.swift` file is emitted,
 * plus a barrel `{outputDir}/ConivaIcons.swift`.
 */
export function generateSwiftFromRuntime(
  icons: SwiftAdapterInput[],
  options?: SwiftAdapterOptions,
): SwiftAdapterResult {
  const framework = options?.framework ?? 'swiftui';
  const outputDir = options?.outputDir ?? 'Sources';
  const packageName = options?.packageName ?? 'ConivaIcons';
  const minimumTarget = options?.minimumDeploymentTarget ?? '16.0';

  const files: Array<{ path: string; contents: string }> = [];
  const diagnostics: PlatformDiagnostic[] = [];
  const componentNames: string[] = [];

  for (const { icon, meta: _meta, variants } of icons) {
    // Check capabilities and collect diagnostics
    for (const variant of variants) {
      const diags = checkPlatformCapabilities(
        SWIFT_CAPABILITIES,
        icon.id,
        variant.variant.id,
        variant,
      );
      diagnostics.push(...diags);
    }

    // Apply downgrade rules to get safe payloads
    const downgraded = variants.map((v) =>
      applyDowngradeRules('swift', v, diagnostics, icon.id),
    );

    const componentName = toSwiftIdentifier(icon.name || icon.id);
    componentNames.push(componentName);

    const code =
      framework === 'swiftui'
        ? generateSwiftUIComponent(componentName, icon, downgraded, minimumTarget)
        : generateUIKitComponent(componentName, icon, downgraded, minimumTarget);

    files.push({
      path: `${outputDir}/${componentName}.swift`,
      contents: code,
    });
  }

  // Barrel file
  const barrelLines = [
    `// ${packageName} — generated by Coniva`,
    `// Do not edit manually.`,
    '',
    `import SwiftUI`,
    '',
    ...componentNames.sort().map(
      (name) => `public typealias ${name} = _${name}View`,
    ),
    '',
  ];

  files.push({
    path: `${outputDir}/${packageName}.swift`,
    contents: barrelLines.join('\n'),
  });

  return { files, diagnostics };
}

// ---------------------------------------------------------------------------
// SwiftUI component generation
// ---------------------------------------------------------------------------

function generateSwiftUIComponent(
  name: string,
  icon: Icon,
  _downgraded: DowngradedPayload[],
  _minimumTarget: string,
): string {
  const stateIds = collectStateIds(icon);
  const firstVariant = getFirstVariant(icon);
  const defaultState = firstVariant.defaultState;
  const viewBox = firstVariant.viewBox;

  const lines: string[] = [];
  lines.push('import SwiftUI');
  lines.push('');
  lines.push(`// Generated from icon "${icon.name || icon.id}"`);
  lines.push(`// States: ${stateIds.join(', ')}`);
  lines.push('');

  // State enum
  lines.push(`public enum ${name}State: String, CaseIterable, Sendable {`);
  for (const stateId of stateIds) {
    lines.push(`    case ${toSwiftCase(stateId)} = ${JSON.stringify(stateId)}`);
  }
  lines.push('}');
  lines.push('');

  // View struct
  lines.push(`public struct _${name}View: View {`);
  lines.push(`    public var state: ${name}State`);
  lines.push('    public var size: CGFloat');
  lines.push('    public var color: Color');
  lines.push('    public var animate: Bool');
  lines.push('');
  lines.push(`    public init(`);
  lines.push(`        state: ${name}State = .${toSwiftCase(defaultState)},`);
  lines.push(`        size: CGFloat = ${firstVariant.size},`);
  lines.push(`        color: Color = .primary,`);
  lines.push(`        animate: Bool = true`);
  lines.push(`    ) {`);
  lines.push(`        self.state = state`);
  lines.push(`        self.size = size`);
  lines.push(`        self.color = color`);
  lines.push(`        self.animate = animate`);
  lines.push(`    }`);
  lines.push('');

  // Body
  lines.push('    public var body: some View {');
  lines.push('        let vb = CGRect(');
  lines.push(`            x: ${viewBox[0]}, y: ${viewBox[1]},`);
  lines.push(`            width: ${viewBox[2]}, height: ${viewBox[3]}`);
  lines.push('        )');
  lines.push('');

  // Generate state-based layer rendering
  lines.push('        ZStack {');
  lines.push('            switch state {');
  for (const stateId of stateIds) {
    const state = firstVariant.states[stateId];
    if (!state) continue;
    lines.push(`            case .${toSwiftCase(stateId)}:`);
    const layers = Object.values(state.layers);
    for (const layer of layers) {
      if (layer.path?.d) {
        lines.push(`                Path { path in`);
        lines.push(`                    // Layer "${layer.id}"`);
        lines.push(`                    path.addSVGPath(${JSON.stringify(layer.path.d)})`);
        lines.push(`                }`);
        const fill = resolveFillSwift(layer);
        lines.push(`                .fill(${fill})`);
      }
    }
  }
  lines.push('            }');
  lines.push('        }');
  lines.push('        .frame(width: size, height: size)');
  lines.push('        .animation(animate ? .easeInOut(duration: 0.3) : nil, value: state)');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  // SVG path extension helper
  lines.push('private extension Path {');
  lines.push('    mutating func addSVGPath(_ d: String) {');
  lines.push('        // Simplified SVG path parser for M, L, C, Z commands');
  lines.push('        // Production implementation should use a full SVG path parser');
  lines.push('        let commands = parseSVGPathCommands(d)');
  lines.push('        for cmd in commands {');
  lines.push('            switch cmd {');
  lines.push('            case .moveTo(let x, let y):');
  lines.push('                move(to: CGPoint(x: x, y: y))');
  lines.push('            case .lineTo(let x, let y):');
  lines.push('                addLine(to: CGPoint(x: x, y: y))');
  lines.push('            case .cubicTo(let x1, let y1, let x2, let y2, let x, let y):');
  lines.push('                addCurve(');
  lines.push('                    to: CGPoint(x: x, y: y),');
  lines.push('                    control1: CGPoint(x: x1, y: y1),');
  lines.push('                    control2: CGPoint(x: x2, y: y2)');
  lines.push('                )');
  lines.push('            case .close:');
  lines.push('                closeSubpath()');
  lines.push('            }');
  lines.push('        }');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  // SVG path command types
  lines.push('private enum SVGPathCommand {');
  lines.push('    case moveTo(CGFloat, CGFloat)');
  lines.push('    case lineTo(CGFloat, CGFloat)');
  lines.push('    case cubicTo(CGFloat, CGFloat, CGFloat, CGFloat, CGFloat, CGFloat)');
  lines.push('    case close');
  lines.push('}');
  lines.push('');
  lines.push('private func parseSVGPathCommands(_ d: String) -> [SVGPathCommand] {');
  lines.push('    // Minimal parser — full implementation in production');
  lines.push('    var commands: [SVGPathCommand] = []');
  lines.push('    let scanner = Scanner(string: d)');
  lines.push('    scanner.charactersToBeSkipped = .whitespaces');
  lines.push('    while !scanner.isAtEnd {');
  lines.push('        if scanner.scanString("M") != nil || scanner.scanString("m") != nil {');
  lines.push('            if let x = scanner.scanDouble(), let y = scanner.scanDouble() {');
  lines.push('                commands.append(.moveTo(CGFloat(x), CGFloat(y)))');
  lines.push('            }');
  lines.push('        } else if scanner.scanString("L") != nil || scanner.scanString("l") != nil {');
  lines.push('            if let x = scanner.scanDouble(), let y = scanner.scanDouble() {');
  lines.push('                commands.append(.lineTo(CGFloat(x), CGFloat(y)))');
  lines.push('            }');
  lines.push('        } else if scanner.scanString("C") != nil || scanner.scanString("c") != nil {');
  lines.push('            if let x1 = scanner.scanDouble(), let y1 = scanner.scanDouble(),');
  lines.push('               let x2 = scanner.scanDouble(), let y2 = scanner.scanDouble(),');
  lines.push('               let x = scanner.scanDouble(), let y = scanner.scanDouble() {');
  lines.push('                commands.append(.cubicTo(');
  lines.push('                    CGFloat(x1), CGFloat(y1), CGFloat(x2), CGFloat(y2),');
  lines.push('                    CGFloat(x), CGFloat(y)');
  lines.push('                ))');
  lines.push('            }');
  lines.push('        } else if scanner.scanString("Z") != nil || scanner.scanString("z") != nil {');
  lines.push('            commands.append(.close)');
  lines.push('        } else {');
  lines.push('            _ = scanner.scanCharacter()');
  lines.push('        }');
  lines.push('    }');
  lines.push('    return commands');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// UIKit component generation (stub for completeness)
// ---------------------------------------------------------------------------

function generateUIKitComponent(
  name: string,
  icon: Icon,
  _downgraded: DowngradedPayload[],
  _minimumTarget: string,
): string {
  const stateIds = collectStateIds(icon);
  const firstVariant = getFirstVariant(icon);

  return [
    'import UIKit',
    '',
    `// Generated UIKit view for "${icon.name || icon.id}"`,
    `// States: ${stateIds.join(', ')}`,
    '',
    `public class ${name}View: UIView {`,
    `    public var iconState: String = ${JSON.stringify(firstVariant.defaultState)}`,
    `    public var iconSize: CGFloat = ${firstVariant.size}`,
    `    public var iconColor: UIColor = .label`,
    '',
    '    private let shapeLayer = CAShapeLayer()',
    '',
    '    public override init(frame: CGRect) {',
    '        super.init(frame: frame)',
    '        setupLayer()',
    '    }',
    '',
    '    required init?(coder: NSCoder) {',
    '        super.init(coder: coder)',
    '        setupLayer()',
    '    }',
    '',
    '    private func setupLayer() {',
    '        layer.addSublayer(shapeLayer)',
    '        updatePath()',
    '    }',
    '',
    '    public func setState(_ newState: String, animated: Bool = true) {',
    '        iconState = newState',
    '        if animated {',
    '            let animation = CABasicAnimation(keyPath: "opacity")',
    '            animation.duration = 0.3',
    '            animation.fromValue = 0',
    '            animation.toValue = 1',
    '            shapeLayer.add(animation, forKey: "crossfade")',
    '        }',
    '        updatePath()',
    '    }',
    '',
    '    private func updatePath() {',
    '        // State-specific path data would be embedded here',
    '        setNeedsLayout()',
    '    }',
    '}',
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getFirstVariant(icon: Icon) {
  const key = Object.keys(icon.variants).sort((a, b) => a.localeCompare(b))[0];
  if (!key) throw new Error(`Icon "${icon.id}" has no variants.`);
  return icon.variants[key]!;
}

function collectStateIds(icon: Icon): string[] {
  const ids = new Set<string>();
  for (const variant of Object.values(icon.variants)) {
    for (const stateId of Object.keys(variant.states)) {
      ids.add(stateId);
    }
  }
  return [...ids].sort((a, b) => a.localeCompare(b));
}

function toSwiftIdentifier(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join('');
}

function toSwiftCase(value: string): string {
  const cleaned = value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .join('_');
  return cleaned.charAt(0).toLowerCase() + cleaned.slice(1);
}

function resolveFillSwift(layer: { style: { fill?: { mode: string; value?: string } } }): string {
  const fill = layer.style.fill;
  if (!fill) return 'color';
  if (fill.mode === 'currentColor') return 'color';
  if (fill.mode === 'fixed' && 'value' in fill) {
    return `Color(hex: ${JSON.stringify(fill.value)})`;
  }
  return 'color';
}
